services:
  chatroom-app:
    image: gggray000/chatroom:latest
    network_mode: "host"
    environment:
      - OLLAMA_HOST=127.0.0.1
      - OLLAMA_PORT=11434
      - JWT_SECRET=chat-room-validate
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_TOOL_OPTIONS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
    restart: unless-stopped
