services:
  nginx:
    image: nginx:latest
    container_name: nginx
    network_mode: "host"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx:/var/log/nginx
    restart: unless-stopped
    depends_on:
      - chatroom-app
  app:
    build: .
    environment:
      - CHATROOM_PDF_STORAGE=/data/pdf-storage
    volumes:
      - ./pdf-storage:/data/pdf-storage

  chatroom-app:
    image: gggray000/chatroom:latest
    container_name: chatroom-app
    network_mode: "host"
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_PORT=11434
      - JWT_SECRET=chat-room-validate
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_TOOL_OPTIONS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
      - LANGCHAIN4J_OLLAMA_CHAT_MODEL_MODEL_NAME=gemma3:4b
      - CAP_ADDR=http://127.0.0.1:3000
      - KEY_ID=${KEY_ID}
      - KEY_SECRET=${KEY_SECRET}
    restart: unless-stopped
