spring.application.name=chatroom

# Remove this after JPA is used
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration


spring.datasource.url=jdbc:postgresql://localhost:5432/chat
spring.datasource.username= postgres
spring.datasource.password= Tm@30082003
spring.datasource.driver-class-name= org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.database=postgresql